/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package libsensor

import spock.lang.Specification

class DemoTest extends Specification {

    def "someLibraryMethod returns true"() {
        setup:
        def lib = new Demo()

        when:
        def result = lib.someLibraryMethod()

        then:
        result == true
    }
}
